### ISSUE TITLE
Typo and possible slight inaccuracy with "Debrick" page

### ISSUE THREAD

**Issue by orblivion** [gl-inet/docs3.x#11]
https://github.com/gl-inet/docs3.x/blob/826990ec15119130c5f688fc8b555baec6fd0208/docs/troubleshooting/debrick.md

Two issues:

## Step 3:

"You MUST obey the first and then procedure"

There is a grammatical error in there. It's a little hard to figure out exactly what this is even saying, but I assume it means "You MUST obey each step before continuing to the next".

## Step 5:

"Release your finger when you see the LED has flashed...5 times...B1300"

I can't speak for any other model, but this detail does not match my own experience with the B1300. I just bought one and flashed custom firmware using U-Boot.

I held onto the reset button and plugged in the device, as instructed. What I saw was that the leftmost LED stayed on the whole time. The rightmost LED flashed only 4 times, after which the middle LED turned on and stayed on.

I let go of the restart button at this point, and it turns out this successfully puts the device into U-Boot mode.

I think this blog post is actually a bit more accurate, even though it's condensed: https://blog.gl-inet.com/uboot-flashing/

**Comment by linmq** [comment]
issue 1: It does confusing. We want to make sure users hold the reset button then plugged in the device.

issue 2: The situation of your B1300 LED flashed is right.  For some old B1300, it flashed 5 times. No matter how many times it flashed, the point is to wait until the middle LDE stayed on, then let it go.

Thanks a lot for your feedback. I had update the docs.
