### ISSUE TITLE
Easy tether documentation

### ISSUE THREAD

**Issue by rs3guy** [gl-inet/docs3.x#14]
The entry for auto connection easytether does not work, the script errors out with "/etc/config/easytether: line 4: syntax error: unexpected "else" "

Of course I am not too familiar with bash scripting, but I was able to get it to work by putting an echo before the else.

edit: After doing a bit of searching seems like it needs the the noop `:` to work without any operation done

**Comment by rs3guy** [comment]
Also it seems that the cron implementation on the gl-mt300n-v2 doesn't run the @reboot jobs on a hard shutdown and power on, only on an actual reboot. So that script doesn't even run  unless I specifically ssh into the thing and reboot, or just call it myself.

**Comment by kamran1988** [comment]
> The entry for auto connection easytether does not work, the script errors out with "/etc/config/easytether: line 4: syntax error: unexpected "else" "
> 
> Of course I am not too familiar with bash scripting, but I was able to get it to work by putting an echo before the else.
> 
> edit: After doing a bit of searching seems like it needs the the noop `:` to work without any operation done
>

**Comment by maurer87** [comment]
i fallowed the guide on ( https://docs.gl-inet.com/en/3/app/tether/ ) i have a 300n-v2 ... i did the LEDE driver (generic ) and also tryed both MT drives in the 18.xx ... non worked to install on it .. both tiny and ssl .... 
fully updated unit - 
... any help or advice is welcomed ... i bought this just for this purpose .. i thought my only requirements was openWRT ... i should of downloaded the driver 1st and look at the content .. its based off the Prosser ... my bad (i bought and ben using easytether for over 10 years now) 
-------------------------------------------------------------------------------------------------------
on 8/28/2020
root@GL-MT300N-V2:/tmp# opkg install easytether-usb-tiny_0.8.9-4_arm_cortex-a7_neon-vfpv4.ipk
Unknown package 'easytether-usb-tiny'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for easytether-usb-tiny found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package easytether-usb-tiny.

-----------------------------------------------------------------------------------------------------------

**Comment by linmq** [comment]
Easytether project is not updating and this function is not offically supported by GL.iNet. The [docs](https://docs.gl-inet.com/en/3/tutorials/tether/) is only for reference.
