### ISSUE TITLE
What is the maximum length for the admin password?

### ISSUE THREAD

**Issue by ovizii** [gl-inet/docs3.x#17]
The reason I am asking is because I don'T use passwords but pass phrases and the router accepted my 5-words-long pass phrase but seems to have a maximum length as I couldn't login with that password later on so apparently the password gets cut off after a certain length.

**Comment by linmq** [comment]
the maximum length for the admin password is 32

**Comment by ovizii** [comment]
thx. I googled some more and it seems my problem was not the maximum length but the fact that I used special characters in my password.

**Comment by sasoiliev** [comment]
Hi,

I just hit this issue. I'm tried using 40 character random-generated passwords. I went through the setup process four times due to this issue.

Would be great if the setup UI validated the length of the password.
