### ISSUE TITLE
Can you please point me towards the manual page explaining dnscrypt-proxy settings in GL iNet?

### ISSUE THREAD

**Issue by ovizii** [gl-inet/docs3.x#18]
As the titles says, can you please point me towards the manual page explaining dnscrypt-proxy settings in GL iNet? 

![image](https://user-images.githubusercontent.com/837902/70268996-cd508080-17a1-11ea-9ab8-fb76e5d1f92f.png)

**Comment by dengxinfa** [comment]
This is a list of DNS -proxy server names. When you select a server name, it automatically retrieves the configuration of the server from a configuration file based on the server name. For more information, you can check the configuration file "/usr/share/dnscrypt-proxy/dnscrypt-resolvers.csv".

![image](https://user-images.githubusercontent.com/35254796/70427958-9c798f80-1ab0-11ea-9b89-1e3a00c08264.png)

**Comment by ovizii** [comment]
Thanks. I found way more documentation about those servers here: https://kb.adguard.com/en/general/dns-providers 

btw. it seems that if I use my router as a VPN client (I'm with Ghost Path VPN) all the DNS settings of the router get ignored and the DNS settings of the VPN connection "have priority"...

**Comment by linmq** [comment]
If use router as a VPN client, the DNS will use VPN too, and will ignore the DNS-Proxy.

**Comment by ovizii** [comment]
ok, I see so VPN client and DNS security seem to be mutually exclusive. Thanks.
