### ISSUE TITLE
Can someoen explain "Internet Kill Switch"?

### ISSUE THREAD

**Issue by ovizii** [gl-inet/docs3.x#19]
The description sounds very ambiguous to me, could some please help me understand?

Here is the original description of this menu:

Note: with this option enabled, the router's clients must access the Internet through VPN. If the router is not configured with VPN, the router's clients will not be able to access the network.

What does it mean saying that if the router is not configured with VPN? I am using the router as a VPN client, will that work?
Or does this mean I need to access the router via a VPN client, meaning the router must be the VPN server?

**Comment by linmq** [comment]
The note does confused. How about this following?

Note: with this option enabled, the router must set up and run the client VPN before the router's clients can access the Internet.

=======
Some our customers very care about the privacy, so they want the router to run the vpn client all the time, if the vpn client is not running, the clients are not allow to access the Internet.
========
Thank you very much for your feedback!

**Comment by ovizii** [comment]
Yes, thanks that clarifies the issue.

Here is my suggestion for imporvement:

Note: with this option enabled, you need to setup the router as a VPN client for any clients to be able to connect to the internet.

**Comment by linmq** [comment]
Thank you for your improvement!
