### ISSUE TITLE
Can Chinese encoding GBK and Unicode be supported

### ISSUE THREAD

**Issue by caifenglin** [gl-inet/docs3.x#20]
Many routers on the market still support GBK. This kind of router is set with Chinese SSID, which leads to garbled code and can't be relayed. I hope it can support Chinese GBK and other codes

**Comment by linmq** [comment]
I have tested it. The SSID can be set as Chinese.
What is your model, and firmware version?

**Comment by caifenglin** [comment]
firmware version  is openwrt-gl-mt300a-clean-2.264，model GL-mt300a。
There is also a problem. My router is often disconnected and reconnected in the case of WLAN. It can't be connected stably. When Wan provides the network, there is no such problem. How can I solve it

发送自 Windows 10 版邮件应用

发件人: Leo
发送时间: 2019年12月9日 16:32
收件人: gl-inet/docs3.x
抄送: caifenglin; Author
主题: Re: [gl-inet/docs3.x] Can Chinese encoding GBK and Unicode besupported (#20)

I have tested it. The SSID can be set as Chinese.
What is your model, and firmware version?

**Comment by linmq** [comment]
Your device is still at 2.x version, please upgrade to 3.x version.
https://dl.gl-inet.com/firmware/mt300a/testing/

GL-MT300A is old and discontinued, please try some new devices https://www.gl-inet.com/products/

**Comment by caifenglin** [comment]
root@GL-MT300A:~# opkg update

Downloading http://www.gl-inet.com/openwrt/ramips/2.263/packages/base/Packages.gz.

wget: server returned error: HTTP/1.1 400 Bad Request

Downloading http://www.gl-inet.com/openwrt/ramips/2.263/packages/base/Packages.sig.

wget: server returned error: HTTP/1.1 400 Bad Request

Signature check failed.

Remove wrong Signature file.

Downloading http://www.gl-inet.com/openwrt/ramips/2.263/packages/luci/Packages.gz.

wget: server returned error: HTTP/1.1 400 Bad Request

Downloading http://www.gl-inet.com/openwrt/ramips/2.263/packages/luci/Packages.sig.

 

this  firmware version :

root@GL-MT300A:/etc/opkg# cat /proc/version

Linux version 3.18.27 (alzhao@alzhao-ubuntu) (gcc version 4.8.3 (OpenWrt/Linaro GCC 4.8-2014.04 r47065) ) #10 Mon Nov 13 19:06:57 HKT 2017




how config this distfeeds.conf ?




发送自 Windows 10 版邮件应用
