### ISSUE TITLE
how config new distfeeds.conf the GL-MT300A:?

### ISSUE THREAD

**Issue by caifenglin** [gl-inet/docs3.x#23]
Downloading http://www.gl-inet.com/openwrt/ramips/2.263/packages/base/Packages.gz.
wget: server returned error: HTTP/1.1 400 Bad Request

firmware version:
root@GL-MT300A:/etc/opkg# cat /proc/version
Linux version 3.18.27 (alzhao@alzhao-ubuntu) (gcc version 4.8.3 (OpenWrt/Linaro GCC 4.8-2014.04 r47065) ) #10 Mon Nov 13 19:06:57 HKT 2017

**Comment by linmq** [comment]
看起来你在用很旧的固件。试试升到 3.100 吧。
You are using 2.x firmware version, try to upgrade to 3.100.
[https://dl.gl-inet.com/firmware/mt300a/testing/](https://dl.gl-inet.com/firmware/mt300a/testing/)

如果还想用 2.x 的固件，试试这个
If you still want to use 2.x firmware, try the guide below.
[https://docs.gl-inet.com/en/2/troubleshooting/stop_supporting/](https://docs.gl-inet.com/en/2/troubleshooting/stop_supporting/)
