### ISSUE TITLE
Unable to add WireGuard profile

### ISSUE THREAD

**Issue by prjoni99** [gl-inet/docs3.x#24]
Hello,

I have a MT300N-V2 and I'm unable to add a manual WireGuard profile. The only thing I'm seeing on my WireGuard Client page is azirevpn and Mullvad. If I click on the bottom where it says Setup WireGuard Manually it comes up with another page that has providers with a pulldown menu and it only shows the two providers mentioned above. Am I doing something wrong? I'm trying to setup WireGuard with VPN Unlimited.

Thanks!

<img width="760" alt="CleanShot 2021-01-03 at 14 39 54@2x" src="https://user-images.githubusercontent.com/39714519/103487191-9815c800-4dd1-11eb-8a00-655d9d430d7a.png">

<img width="802" alt="CleanShot 2021-01-03 at 14 38 59@2x" src="https://user-images.githubusercontent.com/39714519/103487172-74eb1880-4dd1-11eb-95a1-38653d30cc27.png">

**Comment by linmq** [comment]
for VPN Unlimited, please export the configs and manual paste here.

![Dingtalk_20210104165347](https://user-images.githubusercontent.com/1535374/103517749-991c2780-4ead-11eb-92b8-d503b6003e90.jpg)

**Comment by linmq** [comment]
You can find the guide here
https://docs.gl-inet.com/en/3/app/wireguard/#wireguard-providers
