### ISSUE TITLE
Issue with X750 docs github link

### ISSUE THREAD

**Issue by Hengjie** [gl-inet/docs3.x#3]
https://docs.gl-inet.com/en/3/setup/spitz/upgrade/ regarding the bit that says `Please refer to github.com/domino-team/openwrt-cc`

The anchor link does not link directly to Github. Instead it links to `https://docs.gl-inet.com/en/3/setup/spitz/github.com/domino-team/openwrt-cc`

**Comment by linmq** [comment]
Thanks for your feedback, we will fix this link as soon as possible.

**Comment by HillTsang** [comment]
We have fixed this issue. Sorry for any inconvenience caused.
