### ISSUE TITLE
Internet via GL.iNet GL-MT300N-V2 is very slow

### ISSUE THREAD

**Issue by varun1622** [gl-inet/docs3.x#33]
Hi,

My internet speed is around 250 Mbps when connected directly to the router. 
When connected via GL.iNet GL-MT300N-V2 the internet speeds are below 5 Mbps. When connected to VPN the speeds are below 2 Mbps. I have configured LAN.
Please advise how to fix the issue.

**Comment by linmq** [comment]
Please post your question on forum.gl-inet.com or send email to support@gl-inet.com
Please give more info like how GL-MT300N-V2 connect to the Internet, what is the firmware version, is it enable the real-time speed and traffic statistics, how you test the speed via cable or via Wi-Fi?
