### ISSUE TITLE
Instructions for SSH are outdated

### ISSUE THREAD

**Issue by danisztls** [gl-inet/docs3.x#36]
Had to configure it as such for it to work.

```config
Host 192.168.8.1
  User root 
  HostKeyAlgorithms +ssh-rsa
  PubkeyAcceptedKeyTypes +ssh-rsa
```

**Comment by alzhao** [comment]
Which product and firmware you are referring to? Maybe just old firmware.

**Comment by linmq** [comment]
Thanks for your suggestion. 
We will consider adding the tutorial, and want to make it as easy as possible for newbies to understand.

**Comment by danisztls** [comment]
> Which product and firmware you are referring to? Maybe just old firmware.

AX1800 (Flint)
v3.208

**Comment by alzhao** [comment]
Can you let me know the ssh tools/system you are using? I tested several and it is OK.

Also let me know the ssh version.

**Comment by MarcOrfilaCarreras** [comment]
I just ran into the same error and just opened a pull request with the solution in the ssh.md file.
