### ISSUE TITLE
Mozilla VPN guide

### ISSUE THREAD

**Issue by aleksandersumowski** [gl-inet/docs3.x#38]
Please provide guide how to use Mozilla VPN

**Comment by linmq** [comment]
Thanks for your feedback.
The best way is to ask Mozilla VPN custom support, they may have solution.
I just google search it, looks like there is a solution [https://github.com/NilsIrl/MozWire](https://github.com/NilsIrl/MozWire)

**Comment by aleksandersumowski** [comment]
I looked at the project, still don't know how to use it with it my router. I'm not a networking/VPN specialist. Woult it really hurt so much to support your customers?

**Comment by linmq** [comment]
Sorry, Mozilla VPN official website doesn't provide a way to export wireguard configuration, so I can't provide this guide. I suggest to switch to other vpn providers like azirevpn or mullvad that can export wireguard configuration.

**Comment by jeffsf** [comment]
Why don't you post on the support forums? 

That way you have some chance of someone helping you. 

GitHub and similar code repositories are generally not support channels.
