### ISSUE TITLE
Frozen GL-AR750S-EXT

### ISSUE THREAD

**Issue by training4** [gl-inet/docs3.x#41]
The device is frozen on 2G. The 2G light is solid and if I try to reset the device it does not reset. If I unplug it from power and attempt power it back on no lights turn on. In order to get the 2G light to turn on I have to before plugging it into power hold down the reset button. The 5G flashes a few times but then the solid 2G light turns on. Any ideas? If I plug into a switch and I am logged into my router it kills the connection so I dont know what IP address it has. What are the options to fix it if possible?

**Comment by linmq** [comment]
Sorry for the inconvenience. Please contact support@glinet.biz for assistance.
