### ISSUE TITLE
[Feature Request] Offline PDF Documentation

### ISSUE THREAD

**Issue by PhiSYS** [gl-inet/docs3.x#43]
Hello!

I was looking for a downloadable full documentation manual for my travel router, so I can have it downloaded in my device prior to connecting a hotel or public network. Currently I would need a internet connection to be able to browse documentation, and that connection should be provided only by the travel router (let's say we want a VPN configuration active).

I think the Github pipeline can be used to generate the Documentation as PDF in [Release Artifacts](https://github.com/gl-inet/docs3.x/releases). There are [tools that convert](https://gist.github.com/justincbagley/ec0a6334cc86e854715e459349ab1446) Markdown in GitHub to HTML/PDF that may be used to automate the conversion in GitLab. (Sorry not to be more specific on GitHub procedures, I only have experience automating things in GitLab pipelines)

Thank you!

**Comment by linmq** [comment]
Hey,

I don't have the PDF version, but you can contact support@glinet.biz, they may have.

As the code is open, you can git clone the code to Gitlab to try the pipelines.

This repository is for docs 3.x. I build all version of docs to the repository of https://github.com/gl-inet/docs-build
You can clone it, but it only text, still need internet connect to access the images.
