### ISSUE TITLE
AR750S (Slate) - Version 3.022 Release?

### ISSUE THREAD

**Issue by HydesIO** [gl-inet/docs3.x#7]
I was wondering if you could tell me when v3.022 will be released?

I have just purchased the AR750S and have to say it's a pretty awesome piece of kit but I am in dire need for the 'Captive Portal' update in this above version.

Many thanks in advance.

**Comment by linmq** [comment]
The testing version of GL-AR750S can be download here https://dl.gl-inet.com/firmware/ar750s/testing/ , download .tar file to upgrade.
